/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.gob.igm.cne.vista;

import ec.gob.igm.cne.dao.TBaseDAO;
import ec.gob.igm.cne.dao.TListadoDocumentosDAO;
import ec.gob.igm.cne.documentos.CodigoBarras;
import ec.gob.igm.cne.documentos.DatosJunta;
import ec.gob.igm.cne.documentos.Verificador;
import ec.gob.igm.cne.utils.Impresion;
import ec.gob.igm.cne.documentos.Item;
import ec.gob.igm.cne.entidades.TUsuario;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.print.PrintException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author jkari
 */
public class FrmReimpresionDocumentos extends javax.swing.JDialog {
    
    //    Add por Joffre Alava
    private TBaseDAO base;
    static TUsuario usuario;
    
    private DefaultTableModel tableModel;
    private List<DatosJunta> listaJuntas;
    private CodigoBarras objCodigoBarras;
    private List<Object[]>lstRazon;
    
    public static String nombreDoc = "Listado de Materiales";//Listado de Materiales (Urbano/Rural)

    /**
     * Creates new form FrmReimpresionDocumentos
     */
    
    
    
    public FrmReimpresionDocumentos(java.awt.Frame parent, boolean modal, TUsuario usuario ) {
        super(parent, modal);
        initComponents();
        
        //add Joffre A
        this.base =     new TBaseDAO();
        this.usuario = usuario;
        cargarRazon(cmbRazon);
        
        //------- ********
        
        String[] cabecera = {"#", "Junta", "Razón"};
        tableModel = new DefaultTableModel(null, cabecera) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        listaJuntas = new ArrayList<>();
        TListadoDocumentosDAO tldDAO = new TListadoDocumentosDAO();
        objCodigoBarras = tldDAO.listarComponentesCodigo(nombreDoc);
    }

    /**
     * Establece el ancho de las columnas de la tabla en base a los porcentajes
     * dados
     *
     * @param table la tabla cuyos anchos de columna se van a establecer
     * @param tablePreferredWidth ancho total de la tabla en pixels
     * @param percentages porcentajes para cada columna (deben sumar 100%)
     */
    public static void setJTableColumnsWidth(JTable table, int tablePreferredWidth,
            double... percentages) {
        double total = 0;
        for (int i = 0; i < table.getColumnModel().getColumnCount(); i++) {
            total += percentages[i];
        }

        for (int i = 0; i < table.getColumnModel().getColumnCount(); i++) {
            TableColumn column = table.getColumnModel().getColumn(i);
            column.setPreferredWidth((int) (tablePreferredWidth * (percentages[i] / total)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTipoEtiqueta = new javax.swing.ButtonGroup();
        btnTipoDocumento = new javax.swing.ButtonGroup();
        txtCodigo = new javax.swing.JTextField();
        btnReimprimir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbRazon = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jrbNormal = new javax.swing.JRadioButton();
        jrbSufragio = new javax.swing.JRadioButton();
        jrbEscrutinio = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jrbGeneral = new javax.swing.JRadioButton();
        jrbExterior = new javax.swing.JRadioButton();
        jrbVotoCasa = new javax.swing.JRadioButton();
        jrbPPL = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        btnReimprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReimprimir.setText("Reimprimir");
        btnReimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReimprimirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Código de Barras:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tipo de etiqueta:");
        jLabel3.setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName(""); // NOI18N

        btnTipoEtiqueta.add(jrbNormal);
        jrbNormal.setSelected(true);
        jrbNormal.setText("Normal");

        btnTipoEtiqueta.add(jrbSufragio);
        jrbSufragio.setText("Día del sufragio");
        jrbSufragio.setEnabled(false);

        btnTipoEtiqueta.add(jrbEscrutinio);
        jrbEscrutinio.setText("Día del escrutinio");
        jrbEscrutinio.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jrbNormal)
                .addGap(29, 29, 29)
                .addComponent(jrbSufragio)
                .addGap(18, 18, 18)
                .addComponent(jrbEscrutinio)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbNormal)
                    .addComponent(jrbSufragio)
                    .addComponent(jrbEscrutinio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnTipoDocumento.add(jrbGeneral);
        jrbGeneral.setSelected(true);
        jrbGeneral.setText("General");
        jrbGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGeneralActionPerformed(evt);
            }
        });

        btnTipoDocumento.add(jrbExterior);
        jrbExterior.setText("Exterior");
        jrbExterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbExteriorActionPerformed(evt);
            }
        });

        btnTipoDocumento.add(jrbVotoCasa);
        jrbVotoCasa.setText("Voto Casa");
        jrbVotoCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbVotoCasaActionPerformed(evt);
            }
        });

        btnTipoDocumento.add(jrbPPL);
        jrbPPL.setText("PPL");
        jrbPPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPPLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jrbGeneral)
                .addGap(18, 18, 18)
                .addComponent(jrbExterior)
                .addGap(26, 26, 26)
                .addComponent(jrbVotoCasa)
                .addGap(18, 18, 18)
                .addComponent(jrbPPL)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbVotoCasa)
                    .addComponent(jrbPPL)
                    .addComponent(jrbExterior)
                    .addComponent(jrbGeneral))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Razón:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tipo de Proceso:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnReimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO : se puede validar que la longitud del codigo ingresado
        // se corresponda con la longitud que de tener nombreDoc
        Item razonSeleccionado=(Item)cmbRazon.getSelectedItem();
        String razon =  razonSeleccionado.getDescription();
        
        if (txtCodigo.getText().length() > 0) {
            //razon = null;
            objCodigoBarras = Verificador.obtenerJunta(nombreDoc, txtCodigo.getText(), objCodigoBarras);
            DatosJunta datosJunta = objCodigoBarras.obtenerDatosDeJunta();
            /*
            Obtener la lista de razones posibles de reimpresion de etiquetas de documentos
             
            List<String> razones = new ArrayList<>();
            razones.add("Razon....................1");
            razones.add("Razon....................................2");
            razones.add("Razon..............................................3");
            razon = FrmRazonReimpresionDocs.createAndShowGUI(this, true, razones);
            /*
            Si el usuario cerro el dialogo FrmRazonReimpresionDocs, entonces
            razon=null
             */
            
            if (razon != null) {
//                Object[] fila = new Object[3];
//                fila[0] = tableModel.getRowCount() + 1;
//                fila[1] = datosJunta.toString();
//                fila[2] = razon;
//                tableModel.addRow(fila);
                listaJuntas.add(datosJunta);
            }
//            txtCodigo.setText("");
            btnReimprimir.requestFocus();
            //txtCodigo.requestFocus();
        }
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnReimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReimprimirActionPerformed
        // TODO add your handling code here:
        // Add por Joffre Alava
        Item razonSeleccionado=(Item)cmbRazon.getSelectedItem();
        String razon =  razonSeleccionado.getDescription();
        java.util.Date fecha = new Date();
        String sTipoVoto ="Voto General";
        String sEscrutinioSufragio = null;
               
        if(jrbVotoCasa.isSelected())
            sTipoVoto = "Voto en Casa";
        if(jrbPPL.isSelected())
            sTipoVoto = "PPL";
        if(jrbExterior.isSelected())
            sTipoVoto = "exterior";
        
                
        if(jrbSufragio.isSelected())
            sEscrutinioSufragio = "S";
        if(jrbEscrutinio.isSelected())
            sEscrutinioSufragio = "E";
                
        if (listaJuntas.size() > 0) {
            for (DatosJunta junta : listaJuntas) {
                try {
                    Impresion.etiquetaDocumentos(junta, sTipoVoto, sEscrutinioSufragio);                    
                    //TODO: SE DEBE ACTUALIZAR EL ESTADO DE LA ETIQUETA EN T_BASE                    
                    // falta revisar los parametros OJO --- OJO
                    // Reeviar tema del usuario 
					//MS 28.01.2021. Se descomenta la línea para que proceda a la inserción del documento reimpreso en la base de datos	
                    base.ingresarReimpresion(junta.getJuntaPK().getCodProvincia(), junta.getJuntaPK().getCodCanton(), junta.getJuntaPK().getCodParroquia(), junta.getJuntaPK().getCodZona(), junta.getJuntaPK().getJunta(), junta.getJuntaPK().getSexo(), this.usuario.getUsuario(), fecha, this.usuario.getUsuario(), "DOCUMENTO", razon, 1, junta.getTag());                    
                    
                } catch (PrintException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error durante la impresión: ", JOptionPane.ERROR_MESSAGE);
                }
            }
            txtCodigo.setText("");
            txtCodigo.requestFocus();
            System.out.println("ok Re-Impresoin");
            this.listaJuntas.remove(0); // eleiminar el unico objJunta
        }
    }//GEN-LAST:event_btnReimprimirActionPerformed

    private void jrbGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGeneralActionPerformed
        // TODO add your handling code here:
        habilitaOpt();
        
    }//GEN-LAST:event_jrbGeneralActionPerformed

    private void jrbVotoCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbVotoCasaActionPerformed
        // TODO add your handling code here:
        habilitaOpt();
    }//GEN-LAST:event_jrbVotoCasaActionPerformed

    private void jrbPPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPPLActionPerformed
        // TODO add your handling code here:
        habilitaOpt();
    }//GEN-LAST:event_jrbPPLActionPerformed

    private void jrbExteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbExteriorActionPerformed
        // TODO add your handling code here:
        habilitaOpt();
    }//GEN-LAST:event_jrbExteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReimpresionDocumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReimpresionDocumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReimpresionDocumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReimpresionDocumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmReimpresionDocumentos dialog = new FrmReimpresionDocumentos(new javax.swing.JFrame(), true, usuario);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void cargarRazon(JComboBox cmbRazon) {
        this.base=new TBaseDAO();
        
        cmbRazon.removeAllItems();
        this.lstRazon=base.cargarRazon();
    
        //MARCOS - INI 01.01.2021
        //Item razon0 = new Item(1,null);
        //cmbRazon.addItem(razon0);
        //////////////////////////////////
        for (Object[] razones : lstRazon) {
            Item razon=new Item(1,razones[0].toString());
            cmbRazon.addItem(razon);
        }
       
    }
    
    public void habilitaOpt(){
        if(jrbGeneral.isSelected() || jrbExterior.isSelected()){
            jrbNormal.setEnabled(true);
            jrbNormal.setSelected(true);
            jrbSufragio.setEnabled(false);
            jrbEscrutinio.setEnabled(false);
        }
        if(jrbVotoCasa.isSelected() || jrbPPL.isSelected()){
            jrbNormal.setEnabled(true);
            jrbNormal.setSelected(true);
            jrbSufragio.setEnabled(true);
            jrbEscrutinio.setEnabled(true);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReimprimir;
    private javax.swing.ButtonGroup btnTipoDocumento;
    private javax.swing.ButtonGroup btnTipoEtiqueta;
    private javax.swing.JComboBox<String> cmbRazon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jrbEscrutinio;
    private javax.swing.JRadioButton jrbExterior;
    private javax.swing.JRadioButton jrbGeneral;
    private javax.swing.JRadioButton jrbNormal;
    private javax.swing.JRadioButton jrbPPL;
    private javax.swing.JRadioButton jrbSufragio;
    private javax.swing.JRadioButton jrbVotoCasa;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
